name: CI
run-name: Codiologist is being built and tested.
on: [push, pull_request]

jobs:
  build-server:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'MongoDB is running'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      PORT: 5000
      MONGO_URI: mongodb://localhost:27017/DigitalTwinsDB
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          cd server
          npm install

      - name: Start server and run tests
        run: |
          cd server
          python3 -m venv venv
          source venv/bin/activate
          pip install -r ./decryption/requirements.txt
          npm run ci-test
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          cd client
          npm install

      - name: Build client
        run: |
          cd client
          npm run build