name: CI
run-name: Codiologist is being built and tested.
on: [push, pull_request]

jobs:
  build-python-component:
    runs-on: ubuntu-latest
    env: 
      CI_RUN: true
      CI_SSH_PRIVATE_KEY: ${{ secrets.CI_SSH_PRIVATE_KEY }}
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v3
  
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y git python3 python3-pip python3-venv

      - name: install swedish locale
        run: |
          sudo locale-gen sv_SE.UTF-8
          sudo update-locale
          locale -a | grep sv_SE

      - name: Create decrypted folder
        run: |
          ls -l
          cd server
          mkdir decrypted_data
          cd ..

      - name: Set up SSH for cloning the private repo
        run: |
          mkdir -p ~/.ssh
          echo "$CI_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      
      - name: Clone the private repo
        run: |
          cd server/decryption/src
          git clone git@github.com:Codiologoist/Restricted.git
          cp -r Restricted/* .
          cd ../../..

      - name: Create python environment and run the app
        run: |
          cd server/decryption
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirement.txt
          cd src
          python3 main.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: decrypted-data
          path: server/decrypted_data
  build-server:
    runs-on: ubuntu-latest
    needs: build-python-component
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017
        options: >-
          --health-cmd "echo 'MongoDB is running'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/DigitalTwinsDB
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node --version
          npm --version
          cd server
          npm install
      
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: decrypted-data
          path: server/

      - name: Start server and run tests
        run: |
          cd server
          npm run ci-test