name: CI
run-name: Codiologist is being built and tested.
on: [push, pull_request]

jobs:
  build-python-component:
    runs-on: ubuntu-latest
    env: 
      CI_RUN: true
      CI_SSH_PRIVATE_KEY: ${{ secrets.CI_SSH_PRIVATE_KEY }}
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v3
  
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y git python3 python3-pip python3-venv

      - name: Create decrypted folder
        run: |
          ls -l
          cd server
          mkdir decrypted_data
          cd ..

      - name: Set up SSH for cloning the private repo
        run: |
          mkdir -p ~/.ssh
          echo "$CI_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      
      - name: Clone the private repo
        run: |
          cd server/decryption/src
          git clone git@github.com:Codiologoist/Restricted.git
          cd ../../..

      - name: Create python environment and run the app
        run: |
          cd server/decryption
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          cd src
          python3 main.py